### ISSUE TITLE
The user should be redirected to login page after signing up. Not to the portfolio page.

### ISSUE THREAD

**Issue by modihere** [ghoshbishakh/freemex17#17]
It would be better if the user is again redirected again to the login page after signing up. And if a user has already registered with Fb or G+ will the account be linked?

**Comment by ankan17** [comment]
Why redirect the user to the login page again? It will be frustrating for the user to enter the username and password again which he/she just entered.

**Comment by ankan17** [comment]
No, if a user has registered with FB or G+ there is no way to interconnect the two since the user won't be able to use the same username
