### ISSUE TITLE
To change the URL mapping

### ISSUE THREAD

**Issue by dungarpan** [ghoshbishakh/freemex17#3]
From the market watch page if we click the **Details** button of any of the stock and in the new page if we click to buy a stock we are taken to the generic  **Buy Stocks** page where we have to select the stock we want to buy again. We want to be redirected directly to the panel where we can buy the stock we selected without having to search for it again.

**Comment by ghoshbishakh** [comment]
@dungarpan Thanks. You are welcome to send a PR

**Comment by ankan17** [comment]
@dungarpan Please check the project now. The **details** button on `Market` page opens a new tab which shows the details of that stock from google finance. There is no requirement of any redirection. Hope this solves the issue.
