### ISSUE TITLE
Update API to fetch stock price

### ISSUE THREAD

**Issue by agrawalo** [ghoshbishakh/freemex17#31]
It looks like API that is currently used to fetch stock price is deprecated. 

There are a couple of options listed in https://blog.rapidapi.com/google-finance-api-alternatives/

**Comment by agrawalo** [comment]
We should check if we can use WebSocket based API, this will help un in getting rid of updating stock prices using a cron job and it will be more real-time.

**Comment by ankan17** [comment]
I am closing this issue since the API is now usable.

```We should check if we can use WebSocket based API, this will help un in getting rid of updating stock prices using a cron job and it will be more real-time.```

But this is a feature we can explore in the future. So, I'll track this on a separate issue.

Thanks, @agrawalo and @Phantsure for your contributions.

**Comment by agrawalo** [comment]
I noticed that this API is no more free to use
